// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	internal "github.com/johnfercher/maroto/internal"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/pkg/props"
)

// TableList is an autogenerated mock type for the TableList type
type TableList struct {
	mock.Mock
}

// BindGrid provides a mock function with given fields: part
func (_m *TableList) BindGrid(part internal.MarotoGridPart) {
	_m.Called(part)
}

// Create provides a mock function with given fields: header, contents, defaultFontFamily, prop
func (_m *TableList) Create(header []string, contents [][]string, defaultFontFamily string, prop ...props.TableList) {
	_va := make([]interface{}, len(prop))
	for _i := range prop {
		_va[_i] = prop[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, header, contents, defaultFontFamily)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
