// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import props "github.com/johnfercher/maroto/pkg/props"

// Text is an autogenerated mock type for the Text type
type Text struct {
	mock.Mock
}

// Add provides a mock function with given fields: text, fontFamily, marginTop, actualCol, qtdCols
func (_m *Text) Add(text string, textProp props.Text, yColOffset float64, xColOffset float64, colWidth float64) {
	_m.Called(text, textProp, yColOffset, xColOffset, colWidth)
}

// GetLinesQuantity provides a mock function with given fields: text, fontFamily, qtdCols
func (_m *Text) GetLinesQuantity(text string, fontFamily props.Text, colWidth float64) int {
	ret := _m.Called(text, fontFamily, colWidth)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, props.Text, float64) int); ok {
		r0 = rf(text, fontFamily, colWidth)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
