version: "2"
run:
  modules-download-mode: readonly

linters:
  default: all
  disable:
    - mnd
    - wsl
    - wsl_v5
    - wastedassign
    - varnamelen
    - testableexamples
    - tagliatelle
    - nolintlint
    - nlreturn
    - musttag
    - ireturn
    - godot
    - godoclint
    - gochecknoglobals
    - funlen
    - exhaustruct
    - embeddedstructfieldcheck
    - depguard
    - cyclop

  settings:
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - commentedOutCode
        - commentedOutImport
        - dupImport
        - stringXbytes
    lll:
      line-length: 140
    wrapcheck:
      ignore-package-globs:
        - github.com/johnfercher/maroto/*
    testifylint:
      enable-all: true
      disable:
        - error-nil
        - float-compare
    revive:
      rules:
        - name: redefines-builtin-id
          severity: warning
          disabled: true
          exclude: [ "" ]
    interfacebloat:
      max: 15
    gosec:
      excludes:
        - G306

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - docs/*
      - cmd/*
      - '(.+)_test\.go'

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$