run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:
    - cmd/*
    - docs/*

linters-settings:
  lll:
    line-length: 140
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - assignOp
      - badCall
      - badCond
      - boolExprSimplify
      - captLocal
      - caseOrder
      - codegenComment
      - commentedOutCode
      - commentedOutImport
      - commentFormatting
      - defaultCaseOrder
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - elseif
      - exitAfterDefer
      - flagDeref
      - flagName
      - ifElseChain
      - mapKey
      - newDeref
      - offBy1
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeSwitchVar
      - underef
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - godot
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - govet
    - gosimple
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
