package processorprovider

import (
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/processor/mappers/propsmapper"
)

// PDFComponent provides the interface of the components that
// will be generated by the provider (Maroto)
type PDFComponent interface {
	core.Component
}

// ProcessorProvider provides an interface with all the methods that
// Maroto provides for pdf builder
type ProcessorProvider interface {
	CreateBarCode(value string, props ...*propsmapper.Barcode) PDFComponent
	CreateMatrixCode(value string, props ...*propsmapper.Rect) PDFComponent
	CreateQrCode(value string, props ...*propsmapper.Rect) PDFComponent
}
