// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	cache "github.com/johnfercher/maroto/v2/internal/cache"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	gofpdf "github.com/johnfercher/maroto/v2/internal/providers/gofpdf"

	mock "github.com/stretchr/testify/mock"
)

// BuilderProvider is an autogenerated mock type for the BuilderProvider type
type BuilderProvider struct {
	mock.Mock
}

type BuilderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderProvider) EXPECT() *BuilderProvider_Expecter {
	return &BuilderProvider_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: cfg, _a1
func (_m *BuilderProvider) Build(cfg *entity.Config, _a1 cache.Cache) *gofpdf.Dependencies {
	ret := _m.Called(cfg, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *gofpdf.Dependencies
	if rf, ok := ret.Get(0).(func(*entity.Config, cache.Cache) *gofpdf.Dependencies); ok {
		r0 = rf(cfg, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gofpdf.Dependencies)
		}
	}

	return r0
}

// BuilderProvider_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type BuilderProvider_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - cfg *entity.Config
//   - _a1 cache.Cache
func (_e *BuilderProvider_Expecter) Build(cfg interface{}, _a1 interface{}) *BuilderProvider_Build_Call {
	return &BuilderProvider_Build_Call{Call: _e.mock.On("Build", cfg, _a1)}
}

func (_c *BuilderProvider_Build_Call) Run(run func(cfg *entity.Config, _a1 cache.Cache)) *BuilderProvider_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Config), args[1].(cache.Cache))
	})
	return _c
}

func (_c *BuilderProvider_Build_Call) Return(_a0 *gofpdf.Dependencies) *BuilderProvider_Build_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BuilderProvider_Build_Call) RunAndReturn(run func(*entity.Config, cache.Cache) *gofpdf.Dependencies) *BuilderProvider_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewBuilderProvider creates a new instance of BuilderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *BuilderProvider {
	mock := &BuilderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
