// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	fontstyle "github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	mock "github.com/stretchr/testify/mock"
)

// CustomFont is an autogenerated mock type for the CustomFont type
type CustomFont struct {
	mock.Mock
}

type CustomFont_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomFont) EXPECT() *CustomFont_Expecter {
	return &CustomFont_Expecter{mock: &_m.Mock}
}

// GetBytes provides a mock function with no fields
func (_m *CustomFont) GetBytes() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBytes")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// CustomFont_GetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBytes'
type CustomFont_GetBytes_Call struct {
	*mock.Call
}

// GetBytes is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetBytes() *CustomFont_GetBytes_Call {
	return &CustomFont_GetBytes_Call{Call: _e.mock.On("GetBytes")}
}

func (_c *CustomFont_GetBytes_Call) Run(run func()) *CustomFont_GetBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomFont_GetBytes_Call) Return(_a0 []byte) *CustomFont_GetBytes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomFont_GetBytes_Call) RunAndReturn(run func() []byte) *CustomFont_GetBytes_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamily provides a mock function with no fields
func (_m *CustomFont) GetFamily() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFamily")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CustomFont_GetFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamily'
type CustomFont_GetFamily_Call struct {
	*mock.Call
}

// GetFamily is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetFamily() *CustomFont_GetFamily_Call {
	return &CustomFont_GetFamily_Call{Call: _e.mock.On("GetFamily")}
}

func (_c *CustomFont_GetFamily_Call) Run(run func()) *CustomFont_GetFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomFont_GetFamily_Call) Return(_a0 string) *CustomFont_GetFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomFont_GetFamily_Call) RunAndReturn(run func() string) *CustomFont_GetFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function with no fields
func (_m *CustomFont) GetFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CustomFont_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type CustomFont_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetFile() *CustomFont_GetFile_Call {
	return &CustomFont_GetFile_Call{Call: _e.mock.On("GetFile")}
}

func (_c *CustomFont_GetFile_Call) Run(run func()) *CustomFont_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomFont_GetFile_Call) Return(_a0 string) *CustomFont_GetFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomFont_GetFile_Call) RunAndReturn(run func() string) *CustomFont_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetStyle provides a mock function with no fields
func (_m *CustomFont) GetStyle() fontstyle.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStyle")
	}

	var r0 fontstyle.Type
	if rf, ok := ret.Get(0).(func() fontstyle.Type); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(fontstyle.Type)
	}

	return r0
}

// CustomFont_GetStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStyle'
type CustomFont_GetStyle_Call struct {
	*mock.Call
}

// GetStyle is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetStyle() *CustomFont_GetStyle_Call {
	return &CustomFont_GetStyle_Call{Call: _e.mock.On("GetStyle")}
}

func (_c *CustomFont_GetStyle_Call) Run(run func()) *CustomFont_GetStyle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomFont_GetStyle_Call) Return(_a0 fontstyle.Type) *CustomFont_GetStyle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomFont_GetStyle_Call) RunAndReturn(run func() fontstyle.Type) *CustomFont_GetStyle_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomFont creates a new instance of CustomFont. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomFont(t interface {
	mock.TestingT
	Cleanup(func())
},
) *CustomFont {
	mock := &CustomFont{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
