// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import maroto "github.com/johnfercher/maroto"
import mock "github.com/stretchr/testify/mock"

// Image is an autogenerated mock type for the Image type
type Image struct {
	mock.Mock
}

// AddFromBase64 provides a mock function with given fields: b64, marginTop, indexCol, qtdCols, colHeight, percent, extension
func (_m *Image) AddFromBase64(b64 string, marginTop float64, indexCol float64, qtdCols float64, colHeight float64, percent float64, extension maroto.Extension) {
	_m.Called(b64, marginTop, indexCol, qtdCols, colHeight, percent, extension)
}

// AddFromFile provides a mock function with given fields: path, marginTop, indexCol, qtdCols, colHeight, percent
func (_m *Image) AddFromFile(path string, marginTop float64, indexCol float64, qtdCols float64, colHeight float64, percent float64) {
	_m.Called(path, marginTop, indexCol, qtdCols, colHeight, percent)
}
