// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Math is an autogenerated mock type for the Math type
type Math struct {
	mock.Mock
}

// GetWidthPerCol provides a mock function with given fields: qtdCols
func (_m *Math) GetWidthPerCol(qtdCols float64) float64 {
	ret := _m.Called(qtdCols)

	var r0 float64
	if rf, ok := ret.Get(0).(func(float64) float64); ok {
		r0 = rf(qtdCols)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}
