// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	mappers "github.com/johnfercher/maroto/v2/pkg/processor/mappers"
	mock "github.com/stretchr/testify/mock"
)

// orderedComponentCreator is an autogenerated mock type for the orderedComponentCreator type
type orderedComponentCreator struct {
	mock.Mock
}

type orderedComponentCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *orderedComponentCreator) EXPECT() *orderedComponentCreator_Expecter {
	return &orderedComponentCreator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: template
func (_m *orderedComponentCreator) Execute(template interface{}) (mappers.Componentmapper, error) {
	ret := _m.Called(template)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 mappers.Componentmapper
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (mappers.Componentmapper, error)); ok {
		return rf(template)
	}
	if rf, ok := ret.Get(0).(func(interface{}) mappers.Componentmapper); ok {
		r0 = rf(template)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mappers.Componentmapper)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(template)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderedComponentCreator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type orderedComponentCreator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - template interface{}
func (_e *orderedComponentCreator_Expecter) Execute(template interface{}) *orderedComponentCreator_Execute_Call {
	return &orderedComponentCreator_Execute_Call{Call: _e.mock.On("Execute", template)}
}

func (_c *orderedComponentCreator_Execute_Call) Run(run func(template interface{})) *orderedComponentCreator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *orderedComponentCreator_Execute_Call) Return(_a0 mappers.Componentmapper, _a1 error) *orderedComponentCreator_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderedComponentCreator_Execute_Call) RunAndReturn(run func(interface{}) (mappers.Componentmapper, error)) *orderedComponentCreator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newOrderedComponentCreator creates a new instance of orderedComponentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOrderedComponentCreator(t interface {
	mock.TestingT
	Cleanup(func())
},
) *orderedComponentCreator {
	mock := &orderedComponentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
