// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	config "github.com/johnfercher/maroto/pkg/v2/config"
	domain "github.com/johnfercher/maroto/pkg/v2/domain"

	internal "github.com/johnfercher/maroto/internal"

	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/pkg/props"

	tree "github.com/johnfercher/go-tree/tree"
)

// Row is an autogenerated mock type for the Row type
type Row struct {
	mock.Mock
}

type Row_Expecter struct {
	mock *mock.Mock
}

func (_m *Row) EXPECT() *Row_Expecter {
	return &Row_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: cols
func (_m *Row) Add(cols ...domain.Col) domain.Row {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 domain.Row
	if rf, ok := ret.Get(0).(func(...domain.Col) domain.Row); ok {
		r0 = rf(cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Row)
		}
	}

	return r0
}

// Row_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Row_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - cols ...domain.Col
func (_e *Row_Expecter) Add(cols ...interface{}) *Row_Add_Call {
	return &Row_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{}, cols...)...)}
}

func (_c *Row_Add_Call) Run(run func(cols ...domain.Col)) *Row_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]domain.Col, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(domain.Col)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Row_Add_Call) Return(_a0 domain.Row) *Row_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Row_Add_Call) RunAndReturn(run func(...domain.Col) domain.Row) *Row_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeight provides a mock function with given fields:
func (_m *Row) GetHeight() float64 {
	ret := _m.Called()

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Row_GetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeight'
type Row_GetHeight_Call struct {
	*mock.Call
}

// GetHeight is a helper method to define mock.On call
func (_e *Row_Expecter) GetHeight() *Row_GetHeight_Call {
	return &Row_GetHeight_Call{Call: _e.mock.On("GetHeight")}
}

func (_c *Row_GetHeight_Call) Run(run func()) *Row_GetHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Row_GetHeight_Call) Return(_a0 float64) *Row_GetHeight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Row_GetHeight_Call) RunAndReturn(run func() float64) *Row_GetHeight_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructure provides a mock function with given fields:
func (_m *Row) GetStructure() *tree.Node[domain.Structure] {
	ret := _m.Called()

	var r0 *tree.Node[domain.Structure]
	if rf, ok := ret.Get(0).(func() *tree.Node[domain.Structure]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tree.Node[domain.Structure])
		}
	}

	return r0
}

// Row_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Row_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Row_Expecter) GetStructure() *Row_GetStructure_Call {
	return &Row_GetStructure_Call{Call: _e.mock.On("GetStructure")}
}

func (_c *Row_GetStructure_Call) Run(run func()) *Row_GetStructure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Row_GetStructure_Call) Return(_a0 *tree.Node[domain.Structure]) *Row_GetStructure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Row_GetStructure_Call) RunAndReturn(run func() *tree.Node[domain.Structure]) *Row_GetStructure_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function with given fields: provider, cell
func (_m *Row) Render(provider domain.Provider, cell internal.Cell) {
	_m.Called(provider, cell)
}

// Row_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Row_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - provider domain.Provider
//   - cell internal.Cell
func (_e *Row_Expecter) Render(provider interface{}, cell interface{}) *Row_Render_Call {
	return &Row_Render_Call{Call: _e.mock.On("Render", provider, cell)}
}

func (_c *Row_Render_Call) Run(run func(provider domain.Provider, cell internal.Cell)) *Row_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Provider), args[1].(internal.Cell))
	})
	return _c
}

func (_c *Row_Render_Call) Return() *Row_Render_Call {
	_c.Call.Return()
	return _c
}

func (_c *Row_Render_Call) RunAndReturn(run func(domain.Provider, internal.Cell)) *Row_Render_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function with given fields: _a0
func (_m *Row) SetConfig(_a0 *config.Maroto) {
	_m.Called(_a0)
}

// Row_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type Row_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - _a0 *config.Maroto
func (_e *Row_Expecter) SetConfig(_a0 interface{}) *Row_SetConfig_Call {
	return &Row_SetConfig_Call{Call: _e.mock.On("SetConfig", _a0)}
}

func (_c *Row_SetConfig_Call) Run(run func(_a0 *config.Maroto)) *Row_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Maroto))
	})
	return _c
}

func (_c *Row_SetConfig_Call) Return() *Row_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *Row_SetConfig_Call) RunAndReturn(run func(*config.Maroto)) *Row_SetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// WithStyle provides a mock function with given fields: style
func (_m *Row) WithStyle(style *props.Style) domain.Row {
	ret := _m.Called(style)

	var r0 domain.Row
	if rf, ok := ret.Get(0).(func(*props.Style) domain.Row); ok {
		r0 = rf(style)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Row)
		}
	}

	return r0
}

// Row_WithStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithStyle'
type Row_WithStyle_Call struct {
	*mock.Call
}

// WithStyle is a helper method to define mock.On call
//   - style *props.Style
func (_e *Row_Expecter) WithStyle(style interface{}) *Row_WithStyle_Call {
	return &Row_WithStyle_Call{Call: _e.mock.On("WithStyle", style)}
}

func (_c *Row_WithStyle_Call) Run(run func(style *props.Style)) *Row_WithStyle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*props.Style))
	})
	return _c
}

func (_c *Row_WithStyle_Call) Return(_a0 domain.Row) *Row_WithStyle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Row_WithStyle_Call) RunAndReturn(run func(*props.Style) domain.Row) *Row_WithStyle_Call {
	_c.Call.Return(run)
	return _c
}

// NewRow creates a new instance of Row. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRow(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Row {
	mock := &Row{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
