// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import maroto "github.com/johnfercher/maroto"
import mock "github.com/stretchr/testify/mock"

// SignHelper is an autogenerated mock type for the SignHelper type
type Signature struct {
	mock.Mock
}

// AddSpaceFor provides a mock function with given fields: label, fontFamily, fontStyle, fontSize, qtdCols, marginTop, actualCol
func (_m *Signature) AddSpaceFor(label string, fontFamily maroto.Family, fontStyle maroto.Style, fontSize float64, qtdCols float64, marginTop float64, actualCol float64) {
	_m.Called(label, fontFamily, fontStyle, fontSize, qtdCols, marginTop, actualCol)
}
