// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import maroto "github.com/johnfercher/maroto"
import mock "github.com/stretchr/testify/mock"

// Signature is an autogenerated mock type for the Signature type
type Signature struct {
	mock.Mock
}

// AddSpaceFor provides a mock function with given fields: label, textProp, qtdCols, marginTop, actualCol
func (_m *Signature) AddSpaceFor(label string, textProp maroto.TextProp, qtdCols float64, marginTop float64, actualCol float64) {
	_m.Called(label, textProp, qtdCols, marginTop, actualCol)
}
