// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Text is an autogenerated mock type for the Text type
type Text struct {
	mock.Mock
}

type Text_Expecter struct {
	mock *mock.Mock
}

func (_m *Text) EXPECT() *Text_Expecter {
	return &Text_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: text, cell, textProp
func (_m *Text) Add(text string, cell *entity.Cell, textProp *props.Text) {
	_m.Called(text, cell, textProp)
}

// Text_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Text_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - text string
//   - cell *entity.Cell
//   - textProp *props.Text
func (_e *Text_Expecter) Add(text interface{}, cell interface{}, textProp interface{}) *Text_Add_Call {
	return &Text_Add_Call{Call: _e.mock.On("Add", text, cell, textProp)}
}

func (_c *Text_Add_Call) Run(run func(text string, cell *entity.Cell, textProp *props.Text)) *Text_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*entity.Cell), args[2].(*props.Text))
	})
	return _c
}

func (_c *Text_Add_Call) Return() *Text_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *Text_Add_Call) RunAndReturn(run func(string, *entity.Cell, *props.Text)) *Text_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinesQuantity provides a mock function with given fields: text, fontFamily, colWidth
func (_m *Text) GetLinesQuantity(text string, fontFamily props.Text, colWidth float64) int {
	ret := _m.Called(text, fontFamily, colWidth)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, props.Text, float64) int); ok {
		r0 = rf(text, fontFamily, colWidth)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Text_GetLinesQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinesQuantity'
type Text_GetLinesQuantity_Call struct {
	*mock.Call
}

// GetLinesQuantity is a helper method to define mock.On call
//   - text string
//   - fontFamily props.Text
//   - colWidth float64
func (_e *Text_Expecter) GetLinesQuantity(text interface{}, fontFamily interface{}, colWidth interface{}) *Text_GetLinesQuantity_Call {
	return &Text_GetLinesQuantity_Call{Call: _e.mock.On("GetLinesQuantity", text, fontFamily, colWidth)}
}

func (_c *Text_GetLinesQuantity_Call) Run(run func(text string, fontFamily props.Text, colWidth float64)) *Text_GetLinesQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(props.Text), args[2].(float64))
	})
	return _c
}

func (_c *Text_GetLinesQuantity_Call) Return(_a0 int) *Text_GetLinesQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Text_GetLinesQuantity_Call) RunAndReturn(run func(string, props.Text, float64) int) *Text_GetLinesQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// NewText creates a new instance of Text. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewText(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Text {
	mock := &Text{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
