// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import maroto "github.com/johnfercher/maroto"
import mock "github.com/stretchr/testify/mock"

// Text is an autogenerated mock type for the Text type
type Text struct {
	mock.Mock
}

// Add provides a mock function with given fields: text, fontFamily, marginTop, actualCol, qtdCols
func (_m *Text) Add(text string, fontFamily maroto.TextProp, marginTop float64, actualCol float64, qtdCols float64) {
	_m.Called(text, fontFamily, marginTop, actualCol, qtdCols)
}
