// Code generated by mockery v1.0.0. DO NOT EDIT.

package internal

import mock "github.com/stretchr/testify/mock"

// Image is an autogenerated mock type for the Image type
type Image struct {
	mock.Mock
}

// AddFromBase64 provides a mock function with given fields: base64, x, y, width, height
func (_m *Image) AddFromBase64(base64 string, x float64, y float64, width float64, height float64) {
	_m.Called(base64, x, y, width, height)
}

// AddFromPath provides a mock function with given fields: path, marginTop, indexCol, qtdCol
func (_m *Image) AddFromPath(path string, marginTop float64, indexCol float64, qtdCol float64) {
	_m.Called(path, marginTop, indexCol, qtdCol)
}
