name: ci
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - feature/**
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.1'

      - name: Build
        run: go build $(go list -f '{{ .Dir }}' ./... | grep -E -v 'cmd|mocks')

      - name: Test
        run: go test -v $(go list -f '{{ .Dir }}' ./... | grep -E -v 'docs|cmd|mocks')